apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zlp6gsyq0-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-98669a71e2.haqa.p3.openshiftapps.com/rhtap/rhtap-qe:816e269933569210d12fcdf0b245622f8f662aa2@sha256:c0b6170bb5eb21f88a48b39ed9612ebef05981b847d791c9aa0338dc8e5f63e1
          name: container-image
